language: ruby
dist: bionic
cache: bundler
travis_retry: 3
rvm:
  - 2.6.6
  - 2.7.1
git:
  depth: 1
addons:
  postgresql: 10
services:
  - postgresql
stages:
  - build
  - test
before_script:
  - 'cp config/app_config.example.yml config/app_config.yml'
  - 'cp config/secrets.example.yml config/secrets.yml'
  - 'bundle exec rails db:create db:migrate'
install:
  - 'rm ${BUNDLE_GEMFILE}.lock'
  - 'eval bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-$PWD/vendor/bundle}'

jobs:
  include:
    - stage: build
      travis_retry: 3
      script: docker build -t abaco .
      install: skip
      before_script:
        - 'cp config/app_config.example.yml config/app_config.yml'
        - 'cp config/secrets.example.yml config/secrets.yml'
      env:
      rvm:
      addons:
        apt:
          packages:
            - docker-ce
      services:
        - docker
