development:
  adapter: postgresql
  encoding: utf8
  database: abaco_development
  pool: 5
  username: abaco
  password: abaco

test:
  adapter: postgresql
  encoding: utf8
  database: abaco_test
  pool: 5
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'abaco' %>
  password: <%= ENV['TRAVIS'] ? '' : 'abaco' %>

production:
  adapter: postgresql
  encoding: utf8
  database: abaco_production
  pool: 5
  username: abaco
  password: abaco
