defaults: &defaults
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: abaco
  password: abaco
  host: localhost
  port: 5432

development:
  <<: *defaults
  database: abaco_development

test:
  <<: *defaults
  database: abaco_test
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'abaco' %>
  password: <%= ENV['TRAVIS'] ? '' : 'abaco' %>

production:
  <<: *defaults
  database: abaco_production
