defaults: &defaults
  secret_key_base: '631abdf566f2eb9d282289b9769373bbdd5d42d08129566c4f8b2ffa9a0bc487f47304c8c67159329238e7cdf03c722c143c28221c8d02927d9f430c3a2a7dc3'
  gdrive:
    cert: <%= Rails.root.join('certs', 'gdrive.p12') %>
    json: <%= Rails.root.join('certs', 'drive.json') %>
    secret: notasecret
    issuer: 'longid@developer.gserviceaccount.com'
    roles:
      owner: [owner@gmail.com]
      writer: [writer@gmail.com, writer2@gmail.com]
  print_hub_data:
    site: 'www.print-hub-page.com'
    user: '<username>'
    password: '<password>'


development:
  <<: *defaults
production:
  <<: *defaults
test:
  <<: *defaults
